### ISSUE TITLE
v0.2 examples

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof-examples#2]
I just copied all examples from v0.1 to v0.2.

@oemof/oemof-developer-group Please feel responsible to adapt the examples (commit yourself).

I would suggest that we remove all examples that do not work right before the release. Who would do this? (see oemof/oemof#382)

**Comment by ckaldemeyer** [comment]
Single examples (Motoric CHP, CCET, BPT) of GenericCHP usage can be derived from: https://github.com/oemof/oemof/pull/349

**Comment by simnh** [comment]
Do we want to remove all the `*_old.py` files from v0.2, or what is their purpose? If its designed to show the differences of versions I would suggest to change `old` suffix to the previous version, in this case v0.1..

**Comment by uvchik** [comment]
We decided to keep them until the new examples are polished. But in my opinion we should remove them before the release. I think one can compare easily between the folders. Or we remove the folders and but them all together in one folder: invest_0.1.py, invest_0.2.py etc.. But I like the folder because users of v0.2. will easily find there examples.

**Comment by ckaldemeyer** [comment]
> We decided to keep them until the new examples are polished. But in my opinion we should remove them before the release. I think one can compare easily between the folders. Or we remove the folders and but them all together in one folder: invest_0.1.py, invest_0.2.py etc.. But I like the folder because users of v0.2. will easily find there examples.

I agree!

**Comment by uvchik** [comment]
In PR #6 I took the view that it is easier to handle the requirements within each example because some examples need special packages. Therefore I created an example for the header. You can do it as you like but maybe we could align our headers over the time. It is very close to the oemof-headers.

```python
# -*- coding: utf-8 -*-

"""
General description:
---------------------
This example is not a real use case of an energy system but an example to show
how a combined heat and power plant (chp) with an extraction turbine works in
contrast to a chp (eg. block device) with a fixed heat fraction. Both chp plants
distribute power and heat to a separate heat and power Bus with a heat and power
demand. The i/o balance plot shows that the fixed chp plant produces heat and 
power excess and therefore needs more natural gas. The bar plot just shows the
difference in the usage of natural gas.

Requirements:
-------------
pip install "oemof>=0.2,<0.3"
pip install matplotlib (to see the bar plot)
pip install git+https://github.com/oemof/oemof_visio.git (to see the i/o balance
 plot)

"""

__copyright__ = "oemof developer group"
__license__ = "GPLv3"

from oemof import solph   # Here starts the example
```

**Comment by birgits** [comment]
I already added those headers in PR #6 (except for the license part), so I hope no-one objects them ;)

**Comment by uvchik** [comment]
Oh sorry, I missed it. I just reviewed the readme/setup file and did not see the changes within the examples. I do not care whether we us `requirements` or `installation requirements` but I definite like the indent. In that way we can add notes in a nicer way than I did with the brackets.

I do not like the colon because it is already marked as a title (we both did that).

```python
"""
(Installation) requirements
---------------------------
The example is made for oemof v0.2.x.

    pip install "oemof>=0.2,<0.3"

The matplotlib is needed to see the plots.

    pip install matplotlib

To see the i/o balance plot oemof-visio has to be installed.

    pip install git+https://github.com/oemof/oemof_visio.git
"""
```

1. What do you prefer `Installation requirements` or just `requirements` ?
2. Shall we use the layout above?

We could add an example  templated to the wiki or the readme file.

**Comment by uvchik** [comment]
```python
# -*- coding: utf-8 -*-

"""
General description
--------------------
This example is not a real use case of an energy system but an example to show
how a combined heat and power plant (chp) with an extraction turbine works in
contrast to a chp (eg. block device) with a fixed heat fraction. Both chp plants
distribute power and heat to a separate heat and power Bus with a heat and power
demand. The i/o balance plot shows that the fixed chp plant produces heat and 
power excess and therefore needs more natural gas. The bar plot just shows the
difference in the usage of natural gas.

Requirements
------------
The example is made for oemof v0.2.x.

    pip install "oemof>=0.2,<0.3"

The matplotlib is needed to see the plots.

    pip install matplotlib

To see the i/o balance plot oemof-visio has to be installed.

    pip install git+https://github.com/oemof/oemof_visio.git
"""

__copyright__ = "oemof developer group"
__license__ = "GPLv3"

from oemof import solph   # Here starts the example
```

**Comment by uvchik** [comment]
- I merged the dev branch into the master. 
- The GenericCHP examples do not work.
- Some example have missing requirements. Be aware that most plots do need the matplotlib.
- A heading does not end with a colon.
- Use `pip install "oemof>=0.2,<0.3"` to install oemof v0.2.x

**Comment by ckaldemeyer** [comment]
> The GenericCHP examples do not work.

Why? Should I have a look later?

**Comment by uvchik** [comment]
>> The GenericCHP examples do not work.
> 
> Why? Should I have a look later?

Why? Good question ;-)

It is not urgent as the examples are just for download but we will announce the existence of this repository with the release. People may want to check out the examples and wonder.

Generally I think that non-existing examples are better than bad or failing examples.

**Comment by ckaldemeyer** [comment]
> Why? Should I have a look later?
> 
> I think you have to add the components to the energy_system.
> 
> The bpt.py is written as a doctest. This might come from the old testing structure.

I haven't changed anything there.

**Comment by ckaldemeyer** [comment]
> Why? Should I have a look later?
> 
>     I think you have to add the components to the energy_system.
> 
>     The bpt.py is written as a doctest. This might come from the old testing structure.
> 
> I haven't changed anything there.

But I can have a look later..
