### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by JohannesSchwenzer** [oemof/oemof-examples#31]
Hi,

I am planning to use oemof and would like to look into the examples to get a hang of things. Unfortunately i get the following error message when running the basic_example.py script

Traceback (most recent call last):
  File "basic_example.py", line 57, in <module>
    from oemof.tools import logger
ModuleNotFoundError: No module named 'oemof.tools'

in the script it says I need version v0.2.3, however if i try to run
 pip3 install 'oemof>=0.2.3' or  pip install 'oemof>=0.2.3' 

I get this error message:

Collecting oemof>=0.2.3
  Could not find a version that satisfies the requirement oemof>=0.2.3 (from versions: 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.9, 0.0.10, 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 0.2.2)
No matching distribution found for oemof>=0.2.3

I am running Linux Ubuntu 18.04 with Python 3.6 
The error message is the same for other modules starting with oemof in other scripts as well. Maybe there was something wrong in the installation process? I tried installing with pip3 and git cloning as well.

Thanks for your help,
Johannes

**Comment by uvchik** [comment]
Sorry, this is the wrong version. At the moment you can install v0.2.2 using

```pip install oemof````

You do not need to specify the version until the v0.3.0 release. If you want to execute a 0.2.x example after the v0.3.0 release you will have to install a 0.2.x version.

I fixed the docstring in the actual version.

**Comment by jnnr** [comment]
Can we close this issue?

**Comment by uvchik** [comment]
@JohannesSchwenzer never replied but the last reply was a year ago.
