### ISSUE TITLE
Add example for combined usage of TESPy and solph

### ISSUE THREAD

**Issue by fwitte** [oemof/oemof-examples#37]
Hi everybody!
In the last dev meeting at Oldenburg the creation of solph energysystem parameters from a TESPy simulation was discussed. We would like to add an example for a ambient temperature dependent COP of a heat pump. In the discussion the task did not seem too time-consuming, so maybe we are able to come up with an example within the next few weeks? @jakob-wo, @p-snft, who is in this, too? 
Have a nice week!

**Comment by jakob-wo** [comment]
Ok, to start somewhere I will make a rough sketch of what I image the example should contain and might look like:
(This code is just a mock-up!)

```python
from oemof import solph
import pandas as pd
import tespy

data = pd.read_csv('weather_data')
T_amb = data['temp_air']

T_low = range(-15, 20, 1)  # Ambient temperatures above 20degC are neglected
# Alternative: T_low = range(min(temp_air), max(temp_air), 1) 
T_high = 35  # Constant flow temperature for now


# In my opinion it is sufficient to hand over the two temperatures only. To modify the components, 
# the states or the refregerant one has to go into the TESPy model.
cops_clc = []
cops_clc = calc_cops_with_tespy(T_low, T_high)  # Calling the model

cops = []
cops = interpolate(cops_clc, T_low, T_amb) 

solph.Transformer(
    label='heat_pump',
    inputs={b_el: Flow(nominal_value=60)},
    outputs={b_th: Flow()},
    conversion_factors={b_el: cops})
```

Is that more or less what you expect the example should do and show, too?

**Comment by fwitte** [comment]
Looks good for me, I will set up a model next week.

**Comment by p-snft** [comment]
We have a Master's student who is willing to contribute to this. What is your current status? (I would propose she starts a prototype in a branch of `oemof-examples`.)

**Comment by fwitte** [comment]
Hi everybody,
here is a working example showing how to loop over different temperatures and different mass flows of the cooling cycle. The underlying TESPy network should be used in the `cacl_cops_with_tespy` function while providing an interface to the ambient temperature parameter (and all other required parameters).
Have a nice day!
[hp_splitter.txt](https://github.com/oemof/oemof-examples/files/3301095/hp_splitter.txt)

**Comment by bneupane2019** [comment]
Hello!!
@fwitte I tried to run the code and got some issues.
1. In condenser parameterization, it is not taking subcooling as true. It says it does not have that attribute.
2. In conderser to value connection parameterization also it doesnot take the set attibute of Td_bp =-5

Neglecting these two, when we run the code, it compiles but have a message of that the terminal temperature difference at superheater is invalid.

**Comment by fwitte** [comment]
Well, that's my fault. You must run the code on the dev version...

Did you install tespy via PyPi or did you clone the repository and run `pip install -e /path/to/your/local/tespy`? You will need remove tespy from PyPi and reinstall it with the second command. Then check out the dev branch in your local repo.

Hope that works!

**Comment by bneupane2019** [comment]
@fwitte 
Thanks. That issue is no more in dev version. But I am curious now with the message of warning in root. It seems like the values of COP is intermittent.

It is not an issue but just wanted to know the reason.

Thankyou!!

**Comment by fwitte** [comment]
You're welcome @bneupane2019. The error messages indicate, that the solver was not able to find a solution for some of the COP calculations (at very small heat pump load).

**Comment by jakob-wo** [comment]
Hi everyone,
how's it going? Is there any progress on the example? @bneupane2019, if you need support or some review let me know!
