### ISSUE TITLE
Review v.0.3.x Examples

### ISSUE THREAD

**Issue by oakca** [oemof/oemof-examples#42]
**Review v.0.3 Examples**

- [x] /basic_example 
- [ ] /electrical

      need graphviz for plots

- [x] /emission_constraint
- [ ] /excel_reader

      need graphviz for plots

- [x] /flexible_modelling
- [x] /generic_chp
- [ ] /jupyter_tutorials

      Jupyfile 1_ and 2_ are added. However 3_ is not working, check last message for more info

- [x] /installation_test
- [x] /invest_non_convex
- [x] /min_max_runtimes
- [x] /plotting_examples
- [x] /simple_dispatch
- [x] /start_and_shutdown_costs
- [x] /storage_balanced_unbalanced
- [x] /storage_investment
- [x] /variable_chp

**Comment by oakca** [comment]
https://github.com/oemof/oemof-examples/commit/0b76b8408aa868530b1611b7fad4d257786222a3 fixes some of the problems in examples. Missing parts can be found above, under non checked tasks.

**Comment by oakca** [comment]
e21f33ded1ab079824a04a651ca06ec00e2081cb removes empty `__init__.py` files.

**Comment by oakca** [comment]
5e762fe3cc0a0fab160b62f66a9c2234f1317854 fixes `Figure 3` and `Figure 4` x-labels in `storage.py`. Before `rot=0`, the x-labels were out of the figure. 

`Line [132, 133]` can be removed, if it is wanted to have x-labels 'storage_elec_balanced', instead of 'balanced'.  However than, x-labels are overlapping if figure is not maximized (full-screen).

**Comment by oakca** [comment]
b82c3b6c7f6a4f2a2a9d508ad3e29d4e96650762 adds copyright and license string to all of the examples. The structure of the doc-strings are changed to have same kind of syntax. An empty `__init__.py` file is removed. Documentation/comments for `emission_constraint.py` is added.

**Comment by p-snft** [comment]
The empty `__init__.py` is actually there for a reason: You may `include` files in directories, where an `__init__.py` is present, regardless of the contents of that file.

**Comment by oakca** [comment]
so should we add `__init__.py` to all of the examples, if that was the intention?

**Comment by p-snft** [comment]
Well, maybe not in this case. I don't see that someone imports the examples. However, it's not an argument that `__init__.py` was empty.

BTW: Great work! Thanks.

**Comment by oakca** [comment]
Unfortunately I could not make `graphviz` function, so someone should run `/electrical` and `/excel_reader` plots, and check if they are correct.

Additionally I will add `/jupyter_examples` of `v.0.2.x` into `v.0.3.x`.

**Comment by oakca** [comment]
e1b922473176c7690cf7cfadc43c4cfca314ff93 adds the `/jupyter_examples` of `oemof` `v0.2.x` into `v0.3.x`.

One file `3_Draw_network_graph` is excluded from the commit, because it was not running. Under section `Create Graph`, following error is present:

`KeyError: "<oemof.solph.network.Transformer: 'pp_chp'>"`

I am guessing it is because of the `oemof.graph` module. So either we remove the chp plant from the file `1_Simple_dispatch_store_results.ipynb` or some changes have to be done in `oemof.graph` module.

**Comment by jakob-wo** [comment]
I will close this Issue.
