### ISSUE TITLE
plotting_examples/storage_investment_plot.py is much slower with v0.4.x of oemof.solph

### ISSUE THREAD

**Issue by BurningTrapezoid** [oemof/oemof-examples#73]
I noticed that the time it takes the storage_investment_plot example to show the first plot is much longer with v0.4.x than with v0.3.x.
To reduce the chance that this is a problem with my environment, I created a new virtual env for each version. 
For v0.3.x I installed the 'oemof' package, 'matplotlib', and 'pyqt5' and I uninstalled 'PyUtillib' 6.0 (which comes as a dependency) and installed 'PyUtillib' 5.8. Then I ran (...)/v0.3.x/plotting_examples/storage_investment_plot.py and it took only a few seconds before the first plot appeared. 
For v0.4.x I used the other env and installed the 'oemof.solph' package and 'pyqt5'. Then I ran (...)/v0.4.x/plotting_examples/storage_investment_plot.py and it took multiple minutes before the first plot appeared.
I used Python 3.8 in both cases.
If the reason for this behavior is something related to my system, I don't know what it might be. Is there the possibility that there might be an issue with solph or the example? And is there additional info that I can give to help to find the problem?

**Comment by fwitte** [comment]
Hi,

thank you reporting. Might be related to this bug https://github.com/oemof/oemof-solph/pull/760, to resolve you might want to try https://github.com/oemof/oemof-solph/releases/tag/v0.4.2.

If it does not work, you might want to post the list of packages installed in your virtual environment here (`pip freeze > requirements.txt`) so others can try to replicate.

Best regards

**Comment by BurningTrapezoid** [comment]
Thanks, that resolved it. 
Funny timing, I must have installed the package just before the hotfix went live on pypi. :)
